default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: kylej
  password: YaeMikoSimp#1
  pool: 5
  timeout: 5000
  port: 5433

development:
  <<: *default
  database: teyvat_archives_development

test:
  <<: *default
  database: teyvat_archives_test

production:
  <<: *default
  database: teyvat_archives_production
  username: teyvat_archives
  password: <%= ENV["TEYVAT_ARCHIVES_DATABASE_PASSWORD"] %>
  port: 5433